# Generated by Django 3.0.7 on 2020-06-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_auto_20200629_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='group',
        ),
    ]
