# Generated by Django 3.0.7 on 2020-06-28 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_remove_todo_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo_app.Group'),
        ),
    ]
