# Generated by Django 3.0.7 on 2020-06-28 18:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_app', '0005_todo_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(through='todo_app.GroupUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
